In [57]:
from pandas import read_csv as rc
from pandas import DataFrame as df
from tqdm import tqdm
import numpy as np
import pandas as pd
from statsmodels.tsa.stattools import adfuller
from datetime import datetime
import matplotlib.pyplot as plt

In [58]:
df_dict = {}

for asset_id in range(1, 14):
    df_dict[f'Asset_{asset_id}'] = rc(f"/Users/ryanlucas/Desktop/G-Research/Data/Asset-{asset_id}.csv")

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [ ]:
features_dict = {}

for asset_id in range(1, 14):
    features_dict[f'Asset_{asset_id}'] = rc(f"/Users/ryanlucas/Desktop/G-Research/Data/Asset-{asset_id}_features.csv")

In [ ]:
features_dict[f'Asset_6']

        Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
0                0     -0.005460      0.000772      7.492500      5.792500
1                1     -0.005460      0.000772      6.632500      5.770000
2                2     -0.005460      0.000372      6.787500      7.502500
3                3     -0.005460      0.000937      7.467500      8.172500
4                4     -0.005460      0.001548      7.270000      8.595000
...            ...           ...           ...           ...           ...
855542      855542      0.001715      0.000045      0.160000      0.138000
855543      855543      0.001601      0.000106      0.196000      0.106000
855544      855544      0.001125      0.000246      0.174000      0.086000
855545      855545      0.000952      0.000201      0.164000      0.206000
855546      855546      0.000722      0.000214      0.256667      0.186667

[855547 rows x 5 columns]

In [ ]:
df_dict[f'Asset_1'].describe().iloc[:, 1:].round(2).to_latex("/Users/ryanlucas/Desktop/feature_desc.txt")

In [ ]:
df_dict[f'Asset_1']

,A1_timestamp,A1_Count,A1_Open,A1_High,A1_Low,A1_Close,A1_Volume,A1_VWAP,A1_Target,minutes_elapsed
Date,,,,,,,,,,
2018-01-01 00:01:00,1514764860,229,13835.194000,14013.800000,13666.11,13850.176000,31.550062,13827.062090,-0.014643,1.0
2018-01-01 00:02:00,1514764920,235,13835.036000,14052.300000,13680.00,13828.102000,31.046432,13840.362590,-0.015037,2.0
2018-01-01 00:03:00,1514764980,528,13823.900000,14000.400000,13601.00,13801.314000,55.061820,13806.068010,-0.010309,3.0
2018-01-01 00:04:00,1514765040,435,13802.512000,13999.000000,13576.28,13768.040000,38.780529,13783.598100,-0.008999,4.0
2018-01-01 00:05:00,1514765100,742,13766.000000,13955.900000,13554.44,13724.914000,108.501637,13735.586840,-0.008079,5.0
...,...,...,...,...,...,...,...,...,...,...
2019-12-30 14:53:00,1577717580,295,7302.598468,7328.900000,7285.75,7303.691429,22.233366,7303.223206,0.001353,893.0
2019-12-30 14:54:00,1577717640,524,7306.661622,7329.000000,7286.00,7305.963333,82.874426,7306.388316,0.001732,894.0
2019-12-30 14:55:00,1577717700,335,7303.397104,7329.000000,7286.00,7303.920000,34.950544,7303.383504,0.000479,895.0
2019-12-30 14:56:00,1577717760,744,7307.206667,7329.000000,7281.01,7301.865683,74.361918,7304.364645,0.000974,896.0
2019-12-30 14:57:00,1577717820,418,7299.977104,7328.999731,7281.01,7303.470000,43.235221,7301.830836,0.001254,897.0

In [ ]:
features_dict['Asset_1']

         Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
0                 0     -0.008725      0.000961    163.624000    169.084000
1                 1     -0.008725      0.000961    217.264000    148.102000
2                 2     -0.008725      0.002481    176.500000    200.314000
3                 3     -0.008725      0.001629    196.488000    191.760000
4                 4     -0.008725      0.003489    189.900000    170.474000
...             ...           ...           ...           ...           ...
1956277     1956277      0.000074      0.001123     18.070849     20.752857
1956278     1956278     -0.001954      0.001303     27.802857     19.845714
1956279     1956279     -0.002773      0.000828     28.114286     29.820000
1956280     1956280     -0.001061      0.002137     24.882857     20.912802
1956281     1956281      0.000643      0.001760     38.548750     40.865000

[1956282 rows x 5 columns]

In [ ]:
avg_ticks_per_min = []

for asset_id in tqdm(range(1, 14), position = 0, leave = True):
    real_dates = [datetime.utcfromtimestamp(value).strftime('%Y-%m-%d %H:%M:%S') for value in df_dict[f'Asset_{asset_id}'][f'timestamp']]
    minutes_elapsed = [abs(pd.to_datetime(value[:10] +  " 00:00:00") - pd.to_datetime(value)).total_seconds()/60 for value in real_dates ]
    features_dict[f'Asset_{asset_id}']['minutes_elapsed'] = minutes_elapsed

 38%|███▊      | 5/13 [42:41<1:08:17, 512.25s/it]

ValueError: Length of values (1956200) does not match length of index (855547)

In [ ]:
features_dict

{'Asset_1':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow  \
 0                 0     -0.008725      0.000961    163.624000    169.084000
 1                 1     -0.008725      0.000961    217.264000    148.102000
 2                 2     -0.008725      0.002481    176.500000    200.314000
 3                 3     -0.008725      0.001629    196.488000    191.760000
 4                 4     -0.008725      0.003489    189.900000    170.474000
 ...             ...           ...           ...           ...           ...
 1956277     1956277      0.000074      0.001123     18.070849     20.752857
 1956278     1956278     -0.001954      0.001303     27.802857     19.845714
 1956279     1956279     -0.002773      0.000828     28.114286     29.820000
 1956280     1956280     -0.001061      0.002137     24.882857     20.912802
 1956281     1956281      0.000643      0.001760     38.548750     40.865000

          minutes_elapsed
 0                    1.0
 1                    2.0
 2                    3.0
 3                    4.0
 4                    5.0
 ...                  ...
 1956277           1436.0
 1956278           1437.0
 1956279           1438.0
 1956280           1439.0
 1956281              0.0

 [1956282 rows x 6 columns],
 'Asset_2':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow  \
 0                 0     -0.002442      0.000709     22.920000     17.450000
 1                 1     -0.002442      0.000709     26.346667     18.086667
 2                 2     -0.002442      0.001689     29.836667     17.933333
 3                 3     -0.002442      0.001831     30.340000     26.566667
 4                 4     -0.002442      0.000317     31.943333     26.773333
 ...             ...           ...           ...           ...           ...
 1953532     1953532      0.000328      0.001508      0.146000      0.892000
 1953533     1953533     -0.005856      0.005465      0.524000      0.600000
 1953534     1953534     -0.007538      0.001391      0.465000      0.640000
 1953535     1953535     -0.003818      0.004459      0.187500      0.345000
 1953536     1953536     -0.002675      0.001231      0.526667      1.415000

          minutes_elapsed
 0                    1.0
 1                    2.0
 2                    3.0
 3                    4.0
 4                    5.0
 ...                  ...
 1953532           1436.0
 1953533           1437.0
 1953534           1438.0
 1953535           1439.0
 1953536              0.0

 [1953537 rows x 6 columns],
 'Asset_3':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow  \
 0                 0     -0.001168      0.000625      0.000990      0.000000
 1                 1     -0.001168      0.000625      0.000990      0.000148
 2                 2     -0.001168      0.002011      0.000000      0.000000
 3                 3     -0.001168      0.001423      0.000000      0.000128
 4                 4     -0.001168      0.000434      0.000000      0.000997
 ...             ...           ...           ...           ...           ...
 1791862     1791862     -0.005206      0.005527      0.001156      0.003567
 1791863     1791863     -0.007718      0.002221      0.003412      0.002106
 1791864     1791864     -0.009136      0.001167      0.002267      0.003901
 1791865     1791865     -0.004945      0.004851      0.002263      0.001554
 1791866     1791866     -0.001356      0.002709      0.001865      0.001269

          minutes_elapsed
 0                  551.0
 1                  552.0
 2                  553.0
 3                  554.0
 4                  555.0
 ...                  ...
 1791862           1436.0
 1791863           1437.0
 1791864           1438.0
 1791865           1439.0
 1791866              0.0

 [1791867 rows x 6 columns],
 'Asset_4':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow  \
 0                 0  1.341294e-07      0.000746      0.000000  2.000000e-06
 1                 1  1.341294e-07      0.000746      0.000000  1.000000e-06
 2                 2  1.341294e-07      0.000731      0.000002  0.000000e+00
 3                 3  1.341294e-07      0.000698      0.000002  0.000000e+00
 4                 4  1.341294e-07      0.000206      0.000001  0.000000e+00
 ...             ...           ...           ...           ...           ...
 1156861     1156861 -1.455999e-03      0.001848      0.000128  1.506000e-04
 1156862     1156862 -4.235160e-03      0.002506      0.000079  1.202000e-04
 1156863     1156863 -6.370378e-03      0.001991      0.000208  1.970000e-04
 1156864     1156864 -2.992416e-03      0.003768      0.000179  3.700000e-05
 1156865     1156865  1.758841e-03      0.004335      0.000178  9.425000e-05

          minutes_elapsed
 0                  874.0
 1                  875.0
 2                  876.0
 3                  877.0
 4                  878.0
 ...                  ...
 1156861           1436.0
 1156862           1437.0
 1156863           1438.0
 1156864           1439.0
 1156865              0.0

 [1156866 rows x 6 columns],
 'Asset_5':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow  \
 0                 0     -0.009984      0.000126      0.000000      0.000900
 1                 1     -0.009984      0.000126      0.000100      0.000000
 2                 2     -0.009984      0.000324      0.000000      0.001200
 3                 3     -0.009984      0.000602      0.000300      0.000000
 4                 4     -0.009984      0.002826      0.000000      0.000000
 ...             ...           ...           ...           ...           ...
 1955135     1955135     -0.000226      0.001060      0.003083      0.002417
 1955136     1955136     -0.003410      0.003127      0.001483      0.002067
 1955137     1955137     -0.005404      0.001992      0.004467      0.004033
 1955138     1955138     -0.002914      0.003425      0.004267      0.004067
 1955139     1955139     -0.000874      0.001879      0.001760      0.001740

          minutes_elapsed
 0                    1.0
 1                    2.0
 2                    3.0
 3                    4.0
 4                    5.0
 ...                  ...
 1955135           1436.0
 1955136           1437.0
 1955137           1438.0
 1955138           1439.0
 1955139              0.0

 [1955140 rows x 6 columns],
 'Asset_6':         Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
 0                0     -0.005460      0.000772      7.492500      5.792500
 1                1     -0.005460      0.000772      6.632500      5.770000
 2                2     -0.005460      0.000372      6.787500      7.502500
 3                3     -0.005460      0.000937      7.467500      8.172500
 4                4     -0.005460      0.001548      7.270000      8.595000
 ...            ...           ...           ...           ...           ...
 855542      855542      0.001715      0.000045      0.160000      0.138000
 855543      855543      0.001601      0.000106      0.196000      0.106000
 855544      855544      0.001125      0.000246      0.174000      0.086000
 855545      855545      0.000952      0.000201      0.164000      0.206000
 855546      855546      0.000722      0.000214      0.256667      0.186667

 [855547 rows x 5 columns],
 'Asset_7':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
 0                 0      0.017655      0.000218      0.000000      0.003000
 1                 1      0.017655      0.000218      0.000000      0.000000
 2                 2      0.017655      0.021866      0.602500      0.600500
 3                 3      0.017655      0.000483      0.611000      0.620500
 4                 4      0.017655      0.000520      0.618500      0.654000
 ...             ...           ...           ...           ...           ...
 1951122     1951122     -0.000890      0.001357      0.039667      0.105317
 1951123     1951123     -0.005538      0.003926      0.053760      0.060480
 1951124     1951124     -0.007057      0.001824      0.067850      0.063767
 1951125     1951125     -0.004594      0.003062      0.042125      0.045875
 1951126     1951126     -0.001949      0.002096      0.030500      0.040150

 [1951127 rows x 5 columns],
 'Asset_8':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
 0                 0      0.002093      0.000150       0.00010       0.00000
 1                 1      0.002093      0.000150       0.00010       0.00000
 2                 2      0.002093      0.000547       0.00130       0.00030
 3                 3      0.002093      0.000798       0.00010       0.00320
 4                 4      0.002093      0.001065       0.00100       0.00260
 ...             ...           ...           ...           ...           ...
 1592066     1592066     -0.005423      0.002775       0.01975       0.01735
 1592067     1592067     -0.008940      0.004246       0.01785       0.01665
 1592068     1592068     -0.023532      0.001548       0.01705       0.01740
 1592069     1592069     -0.006879      0.002956       0.01745       0.01640
 1592070     1592070     -0.001592      0.004021       0.01885       0.01735

 [1592071 rows x 5 columns],
 'Asset_9':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
 0                 0     -0.007382      0.003342      2.450000      2.226667
 1                 1     -0.007382      0.003342      2.246667      2.406667
 2                 2     -0.007382      0.006810      2.898000      3.560000
 3                 3     -0.007382      0.006340      1.640000      3.275000
 4                 4     -0.007382      0.002316      1.452500      2.570000
 ...             ...           ...           ...           ...           ...
 1956025     1956025     -0.000487      0.000896      0.148286      0.188714
 1956026     1956026     -0.003876      0.003562      0.285571      0.176286
 1956027     1956027     -0.006865      0.002459      0.223286      0.214000
 1956028     1956028     -0.003975      0.002945      0.115000      0.112571
 1956029     1956029     -0.002845      0.001127      0.068429      0.243857

 [1956030 rows x 5 columns],
 'Asset_10':         Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
 0                0      0.223482      0.235587      0.000000      0.000000
 1                1      0.223482      0.235587      0.000000      0.000000
 2                2      0.223482      0.000000      0.000000      0.000000
 3                3      0.223482      0.315066      0.000000      9.500000
 4                4      0.223482      0.309704      0.000000      0.000000
 ...            ...           ...           ...           ...           ...
 670492      670492     -0.003179      0.003742      2.282375      1.832500
 670493      670493     -0.006065      0.002919      2.865550      2.437500
 670494      670494     -0.006613      0.000526      1.888000      3.673900
 670495      670495     -0.002201      0.005460      3.347750      3.981500
 670496      670496     -0.000959      0.000768      0.934933      2.680567

 [670497 rows x 5 columns],
 'Asset_11':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
 0                 0      0.007393      0.000012        0.4200        0.0000
 1                 1      0.007393      0.000012        0.0000        0.0000
 2                 2      0.007393      0.000762        0.0000        0.0000
 3                 3      0.007393      0.003161        0.0000        0.0000
 4                 4      0.007393      0.000251        0.0000        0.0000
 ...             ...           ...           ...           ...           ...
 1701256     1701256     -0.004527      0.002516        0.3050        0.2400
 1701257     1701257     -0.007287      0.002432        0.2940        0.1800
 1701258     1701258     -0.006578      0.000759        0.5075        0.0925
 1701259     1701259     -0.003424      0.002996        0.5320        0.3660
 1701260     1701260     -0.000068      0.002643        0.1050        0.0350

 [1701261 rows x 5 columns],
 'Asset_12':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
 0                 0      0.147961      0.011684      0.000000      0.000000
 1                 1      0.147961      0.011684      0.000000      0.000000
 2                 2      0.147961      0.136576      0.000000      0.000000
 3                 3      0.147961      0.000426      0.000000      0.000000
 4                 4      0.147961      0.043059      0.000000      0.000000
 ...             ...           ...           ...           ...           ...
 1778744     1778744     -0.001233      0.002224      0.000254      0.000289
 1778745     1778745     -0.004247      0.002867      0.000395      0.000350
 1778746     1778746     -0.007264      0.002534      0.000190      0.000268
 1778747     1778747     -0.004817      0.002669      0.000322      0.000521
 1778748     1778748     -0.002270      0.002685      0.000270      0.000209

 [1778749 rows x 5 columns],
 'Asset_13':          Unnamed: 0  VWAP_Delta_5  VWAP_Delta_1  Upper Shadow  Lower Shadow
 0                 0      0.006461      0.009376      0.000000      0.000160
 1                 1      0.006461      0.009376      0.000000      0.000000
 2                 2      0.006461      0.032636      0.000000      0.000000
 3                 3      0.006461      0.003033      0.000190      0.000054
 4                 4      0.006461      0.004393      0.000000      0.000000
 ...             ...           ...           ...           ...           ...
 1874555     1874555     -0.001405      0.001578      0.000065      0.000101
 1874556     1874556     -0.006028      0.003836      0.000065      0.000061
 1874557     1874557     -0.007631      0.001683      0.000081      0.000113
 1874558     1874558     -0.003538      0.003908      0.000124      0.000081
 1874559     1874559     -0.001059      0.002129      0.000136      0.000089

 [1874560 rows x 5 columns]}